databases:
  - name: farmat-db
    plan: free
    databaseName: farmdb
    user: farmat_user

services:
  - type: web
    plan: free
    name: farmat
    runtime: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y libc6-dev
      ./build.sh
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
