databases:
  - name: farmat-db
    plan: free
    databaseName: farmdb
    user: farmat_user

services:
  - type: web
    name: farmat
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
