# Generated by Django 4.2.13 on 2024-05-20 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "animal_picture",
                    models.ImageField(blank=True, default="fall.png", upload_to=""),
                ),
                ("animal_id", models.AutoField(primary_key=True, serialize=False)),
                ("animal_name", models.CharField(max_length=50)),
                ("animal_type", models.CharField(max_length=50)),
                ("animal_age", models.CharField(max_length=10)),
                ("animal_location", models.CharField(max_length=30)),
                ("animal_breed", models.CharField(max_length=20)),
                ("available", models.IntegerField()),
                ("animal_price", models.IntegerField()),
                ("animal_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "profile_picture",
                    models.ImageField(blank=True, default="fall.png", upload_to=""),
                ),
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "profile_picture",
                    models.ImageField(blank=True, default="fall.png", upload_to=""),
                ),
                ("farmer_id", models.AutoField(primary_key=True, serialize=False)),
                ("contact", models.CharField(max_length=25)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(auto_now_add=True)),
                ("animal_name", models.CharField(max_length=30)),
                ("quantity", models.IntegerField(blank=True)),
                (
                    "order_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("denied", "Denied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="api.animal",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="api.customer",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="api.farmer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="api.farmer",
            ),
        ),
    ]
